### ISSUE TITLE
Configure leader election in oathkeeper-maester

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [ory/k8s#100]
**Is your feature request related to a problem? Please describe.**
Currently we can't reliably scale oathkeeper-maester when it runs in `controller mode`, because every replica would try to re-create the ConfigMap with Rules.

**Describe the solution you'd like**
We should configure leader election by adding `--enable-leader-election=true` flag to the controller arguments

**Describe alternatives you've considered**
If there's always only one replica, there's no problem.

**Additional context**
We can't add this flag until https://github.com/ory/oathkeeper-maester/issues/34 is fixed. If it is `true`, the internal logger is triggered.

**Comment by aeneasr** [comment]
I am closing this issue as it has not received any engagement from the community or maintainers in a long time. That does not imply that the issue has no merit. If you feel strongly about this issue

- open a PR referencing and resolving the issue;
- leave a comment on it and discuss ideas how you could contribute towards resolving it;
- open a new issue with updated details and a plan on resolving the issue.

We are cleaning up issues every now and then, primarily to keep the 4000+ issues in our backlog in check and to [prevent](https://www.jeffgeerling.com/blog/2020/saying-no-burnout-open-source-maintainer) [maintainer](https://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes) [burnout](https://docs.brew.sh/Maintainers-Avoiding-Burnout). Burnout in open source maintainership is a [widespread](https://opensource.guide/best-practices/#its-okay-to-hit-pause) and serious issue. It can lead to severe personal and health issues as well as [enabling catastrophic](https://haacked.com/archive/2019/05/28/maintainer-burnout/) [attack vectors](https://www.gradiant.org/en/blog/open-source-maintainer-burnout-as-an-attack-surface/).

Thank you to anyone who participated in the issue! 🙏✌️
