### ISSUE TITLE
Hydra / Maester: Make the install of custom CRDs optional and rely on Helm 3 convention for CRDs installation

### ISSUE THREAD

**Issue by PoulpiFr** [ory/k8s#105]
**Is your feature request related to a problem? Please describe.**
My current dev workflow (Skaffold + Helm 3) is doing a lot of `helm upgrade` when iterating. Hydra Maester chart is taking a long time to be upgraded, due to the usage of a Job to install CRDs.

As there are now standardized way of installing CRDs with Helm 3 that would be faster / more standard, would it be possible to offer a way to rely on them?

**Describe the solution you'd like**
- Make the installation of CRDs through a job at each `helm upgrade` **optional** with a new value parameter (that can default to true)
- Move the CRD file into a `/crds` directory so that Helm 3 can install them at the first chart install only.

**Describe alternatives you've considered**
I see no other solution. Change my dev workflow maybe? 

However, skaffold and Helm seems to be popular choices.

**Additional context**
https://developer.ibm.com/blogs/kubernetes-helm-3/#simplified-custom-resource-definition-crd-support
https://github.com/helm/helm/issues/5871
https://github.com/helm/helm/pull/6243

-> Please note that this would prevent this chart from updating the CRDs without changing its apiVersion from what I understand. While the current behavior is doing it.

If you're OK with the approach, I can do a PR.

**Comment by aeneasr** [comment]
We have unfortunately not yet worked with Helm 3 so I have personally very little input on that. What's important for us is to keep Helm 2 compatibility.

Regarding moving the CRD (previously this was done with hooks iirc) - how would that affect CRD updates?

However, I think this really boils down to another issue, which is this one: https://github.com/ory/k8s/issues/103

It appears that this flag has no effect which might actually be what you're looking for?

**Comment by aeneasr** [comment]
Yeah, the `/crd` directory only works in Helm 3, I don't think it would be a good idea to make these charts incompatible with helm 2.

**Comment by Demonsthere** [comment]
Closed by https://github.com/ory/k8s/pull/235 :)
