### ISSUE TITLE
Cannot specify "password" grant_type

### ISSUE THREAD

**Issue by sneko** [ory/k8s#106]
Hi,

I would like to specify the grant_type `password` but it's not in the CRD specification:
https://github.com/ory/hydra-maester/blob/master/config/crd/bases/hydra.ory.sh_oauth2clients.yaml#L394-L398

so I get the error:
```spec.grantTypes in body should be one of [client_credentials authorization_code implicit refresh_token]```

Thank you,

**Comment by aeneasr** [comment]
https://www.ory.sh/docs/hydra/limitations#resource-owner-password-credentials-grant-type-rocp

**Comment by sneko** [comment]
Hi @aeneasr , I would like to make ORY Hydra the main tool to generate tokens.

Since I'm migrating to Hydra, my current AuthService needs to plug into it to authenticate the user (AND I'm not dealing with OAuth2.0 with this).

How can I achieve that if that's not allowed with Hydra? Maybe I missed something... 😢 

Thank you,

**Comment by aeneasr** [comment]
You could ask the question with more details in https://community.ory.sh - the community will be able to answer you :)
