### ISSUE TITLE
Set additional sidecar + volumes

### ISSUE THREAD

**Issue by sneko** [ory/k8s#111]
Hi,

To make a secure connection to the storage when using Google Cloud SQL, Google advises using a proxy that will manage credentials through secrets (https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine?hl=fr)... it implies having this container aside the Hydra container.

See chart examples:
https://github.com/helm/charts/blob/master/stable/sonatype-nexus/templates/deployment-statefulset.yaml#L208-L210
https://github.com/helm/charts/blob/master/stable/sonatype-nexus/templates/deployment-statefulset.yaml#L115-L117

Same here:
https://github.com/helm/charts/tree/master/stable/grafana
they use extraContainers and extraVolumes.

Having this inside your chart would help 👍 

Thank you,

**Comment by aeneasr** [comment]
Would it be possible to do this via `requirements.yml` instead - or by executing a specific `helm install` configuration for https://hub.helm.sh/charts/rimusz/gcloud-sqlproxy ? In case you don't trust arbitrary helm repos - `rimusz` is one of Helm's founders.

**Comment by sneko** [comment]
If using `requirements.yaml` the SQLProxy chart will not be used if a property like `sqlproxy.enable = false` is set, right?

It could work but from my understanding the SQLProxy would be in another pod (maybe on another node), so is it secure enough compared to communicating on the localhost and then securely to Google servers?

**Comment by aeneasr** [comment]
I think you can set the node affinity using `nodeAffinity`. That way you can co-locate resources on Kubernetes. Traffic would always go through the network as far as I understand, as you're calling the proxy using a FQDN and DNS. I'd like to avoid platform specifica in these charts.

**Comment by sneko** [comment]
In addition to nodeAffinity I should also add policies to prevent any other pod to use the SQL proxy (whereas as an extra container since the port is not exposed through a service no pod can access it).

But I understand your point 👍

**Comment by aeneasr** [comment]
Hm yeah I'm happy to review options how to lower the bar for that here :)

**Comment by aeneasr** [comment]
I am closing this issue as it has not received any engagement from the community or maintainers in a long time. That does not imply that the issue has no merit. If you feel strongly about this issue

- open a PR referencing and resolving the issue;
- leave a comment on it and discuss ideas how you could contribute towards resolving it;
- open a new issue with updated details and a plan on resolving the issue.

We are cleaning up issues every now and then, primarily to keep the 4000+ issues in our backlog in check and to [prevent](https://www.jeffgeerling.com/blog/2020/saying-no-burnout-open-source-maintainer) [maintainer](https://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes) [burnout](https://docs.brew.sh/Maintainers-Avoiding-Burnout). Burnout in open source maintainership is a [widespread](https://opensource.guide/best-practices/#its-okay-to-hit-pause) and serious issue. It can lead to severe personal and health issues as well as [enabling catastrophic](https://haacked.com/archive/2019/05/28/maintainer-burnout/) [attack vectors](https://www.gradiant.org/en/blog/open-source-maintainer-burnout-as-an-attack-surface/).

Thank you to anyone who participated in the issue! 🙏✌️
