### ISSUE TITLE
Maester not synchronizing when upgrading the chart?

### ISSUE THREAD

**Issue by sneko** [ory/k8s#112]
**Describe the bug**

I modified the issuer url and upgraded the chart after that.

- I'm unable generate tokens with good credentials
- when looking at `/clients` it returns `null`

I do see the OAuth2Client resources with kubectl, same for the secrets (same than before the upgrade).

**To Reproduce**

DSN: memory

**Expected behavior**

That Hydra pod is fully synchronized with all clients

**Additional context**

When upgrading the issuer URL, only Hydra pod has been restarted, not the maester one.

I tried to force restarting the maester one but nothing happens except it says `Successfully Reconciled` for all my clients...

In the Hydra pod I just see that when trying to log in:
```
time="2020-01-20T16:41:25Z" level=info msg="started handling request" method=POST remote="127.0.0.1:57982" request=/oauth2/token
time="2020-01-20T16:41:25Z" level=error msg="An error occurred" debug="Not Found" description="Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)" error=invalid_client
time="2020-01-20T16:41:25Z" level=info msg="completed handling request" measure#hydra/public: https://localhost:4444/.latency=868013 method=POST remote="127.0.0.1:57982" request=/oauth2/token status=401 text_status=Unauthorized took="868.013µs"
```

**Comment by aeneasr** [comment]
https://github.com/ory/hydra-maester/issues/43
