### ISSUE TITLE
External secret for Oathkeeper JWKS data

### ISSUE THREAD

**Issue by FredrikAppelros** [ory/k8s#120]
**Is your feature request related to a problem? Please describe.**
When configuring Oathkeeper there is no mechanism in the chart to depend on an externally deployed secret for the JWKS data.

**Describe the solution you'd like**
There should be some way to configure the chart to use a secret that is already present in the deployment environment. It would then mount this secret instead of the one which is always created that can be configured using `oathkeeper.mutatorIdTokenJWKs`.

**Describe alternatives you've considered**
The most straightforward alternative is to just use the `oathkeeper.mutatorIdTokenJWKs` configuration value. The caveat of this is that you then need to make this secret available in plain text to Helm as it wants to encode and create the secret for you. This could have security implications depending on where Helm is running.

**Additional context**
None

**Comment by aeneasr** [comment]
Do you have any suggestions how we could set up the helm file to support that?

**Comment by FredrikAppelros** [comment]
I could give a go at it and throw a PR your way with an attempt. It might take a while though until I find some time for it.

**Comment by aeneasr** [comment]
Ok :)
