### ISSUE TITLE
Migrate Helm to v3

### ISSUE THREAD

**Issue by aeneasr** [ory/k8s#123]
**Is your feature request related to a problem? Please describe.**

Helm charts and the release pipeline have been written using Helm v2. We want to deprecate support for Helm v2 and move to Helm v3 as it is way easier to install and set up and comes with other improvements.

**Describe the solution you'd like**

All helm charts should be updated to work with v3. In the optimal case, they would be backwards compatible.

The CI chain also needs to be upgraded to Helm v3.

**Comment by aeneasr** [comment]
https://github.com/ory/k8s/commit/44f3feee2ee0a17b4034233843252cc08f08d1d6#r38146542

**Comment by schwabing** [comment]
We have started with this, as well as adding to the charts for Kratos. Shouldn't everything hive be renamed to kratos, including helm chart names? Any other advice?

**Comment by aeneasr** [comment]
> Shouldn't everything hive be renamed to kratos, including helm chart names? Any other advice?

Yeah, there's also an open PR for that but it's response pending from the author so if you want to go ahead and do that please do :)

**Comment by schwabing** [comment]
Done :) Almost, at least: https://github.com/ory/k8s/pull/128
