### ISSUE TITLE
Add documentation for kratos chart

### ISSUE THREAD

**Issue by Morishiri** [ory/k8s#141]
**Is your feature request related to a problem? Please describe.** 

It's related to a problem setting up basic kratos. I get a lot of validation errors and I need to fix them one by one, because I don't know what's required and what isn't. It fails in runtime, because it cannot validate config.

**Describe the solution you'd like** 

A documentation like e.g. hydra has https://k8s.ory.sh/helm/hydra.html which would tell me exactly which values are required.

**Describe alternatives you've considered** 

I found this document: https://www.ory.sh/kratos/docs/reference/configuration but it looks like it's not matching everything. Additionally, it looks like the defaults are not taken into account in helm chart.

**Additional context** 

N/A

**Comment by aeneasr** [comment]
Yup, good point! Help appreciated

**Comment by cobraz** [comment]
Hi @Morishiri! If you are looking for documentation, check #148.
