### ISSUE TITLE
hydra helm chart does not seem to be using the urls.login, consent & logout values in the deployment

### ISSUE THREAD

**Issue by SriShravyaBasavaraju** [ory/k8s#143]
**Describe the bug**

hydra provides environment variables to set the login, consent & logout URLs. But the helm chart doesn't seem to be using those values in the deployment file. Currently, only the following variables are being used in the chart: URLS_SELF_ISSUER, SECRETS_SYSTEM, SECRETS_COOKIE

**To Reproduce**

Install hydra helm chart version 0.0.1 using helm v3

**Expected behavior**

helm values of urls.logout, urls.login, urls.consent environment variables are to be used in the hydra deployment.

- Version: helm v3, hydra chart 0.0.1
- Environment: MacOS

I can submit a PR fixing this issue.

**Comment by aeneasr** [comment]
They are being set, but using a ConfigMap with VolumeMount and the `--config` flag.

**Comment by SriShravyaBasavaraju** [comment]
Thanks! missed that part. Tested the chart with login/consent/logout url configuration, seems to be working fine. Closing this issue.
