### ISSUE TITLE
[Helm] Ensure kubernetes version label is always present

### ISSUE THREAD

**Issue by ermik** [ory/k8s#15]
The current code depends on `Chart.AppVersion` to be present, and while it is unlikely that it isn't — we should include a fallback.

**Comment by aeneasr** [comment]
What exactly is the issue here? You can check out the release pipeline here: https://github.com/ory/k8s/blob/master/.circleci/config.yml#L14

**Comment by ermik** [comment]
This doesn't refer to build artifacts, rather it is one of [best practices](https://helm.sh/docs/chart_best_practices/#standard-labels) to include labels (annotations) to the generated manifests explicitly, rather than relying on other tools in the deployment pipeline (Tiller, kubelet) to write them when manifests are _applied_ in the cluster.

This issue can be closed by adding a `.tpl` partial with something like the following:

```yaml
{{- define "labels.app"}}
app: {{ .Chart.Name | quote }}
{{- end }}
{{- define "labels.version" }}{{- $serviceVersion := printf "v%s" .Chart.Version }}
version: {{ $serviceVersion | quote }}
{{- end }}
{{- define "labels.helm" }}
chart: {{ printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") | quote }}
release: {{ .Release.Name | quote }}
heritage: {{ .Release.Service | quote }}
{{- end }}
```

and using this partial in the following way:
```yaml
  name: {{ .Values.somename | quote }}
  labels:
    {{- include "labels.app" . | indent 4 }}
    {{- include "labels.version" . | indent 4 }}
    {{- include "labels.helm" . | indent 4 }}
```
in each of the templated objects.

There are more annotations that are suggested in best practices, but `helm.sh` and app/version are ones I (personally) think are important.

**Comment by aeneasr** [comment]
Oh ok, I see - the current way this is generated is simply from `helm create .` so there's definitely room for improvement!

**Comment by ermik** [comment]
I took another look and I see that I missed some of the work that has already been done. Additionally, the example above shows classic labels — I linked to current best practices to avoid confusion. I've reformatted this issue to make sure it's clearer and published the PR implementing the changes.
