### ISSUE TITLE
Kratos chart doesn't insist on all the required configuration

### ISSUE THREAD

**Issue by simeonmiteff** [ory/k8s#153]
**Describe the bug**

By careful eyeballing of the kratos config schema, I've figured out that 0.3.0 requires:
- `kratos.config.dsn`
- `kratos.config.identity.traits.default_schema_url`
- `kratos.config.courier.smtp.connection_uri`
- `kratos.config.urls.self.public`
- `kratos.config.urls.self.admin`

It doesn't seem like the chart enforces presence of the latter 4 keys in the configuration. The [chart documentation](https://k8s.ory.sh/helm/kratos.html) says the two required values are:
- `kratos.config.dsn`
- `kratos.config.secrets.session`

I have opened #152 to clarify whether `kratos.config.secrets.session` is really needed.

**To Reproduce**

1. Follow the [chart documentation](https://k8s.ory.sh/helm/kratos.html)
2. `helm install`
3. Observe kratos fail to start without the above required configuration

**Expected behavior**

1. Documentation directs the chart user to set the required configuration
2. The chart enforces required configuration

**Environment**

- Version: chart version 0.1.0

**Comment by aeneasr** [comment]
I believe this has been improved since the issue has been opened originally!
