### ISSUE TITLE
Use persistent volume when using ORY Kratos with SQLite on Disk

### ISSUE THREAD

**Issue by tnm0113** [ory/k8s#159]
**Describe the bug**

I install kratos using helm and set automigrate to true, config.dsn to sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc in values.yaml. Everything seems fine, but when kratos enters flow /self-service/browser/flows/login, it returns error message:sqlite create: no such table: selfservice_login_requests and message:sqlite create: no such table: selfservice_errors, and status code 500

**To Reproduce**

1. Set automigrate to true, config.dsn to sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc in values.yaml
2. Run install kratos and kratos-selfservice-ui-node, oathkeeper using helm, configure to produce scenario like Quick start example
3. Request to /dashboard, its redirected to /.ory/kratos/public/self-service/browser/flows/login, kratos's log shows request=/self-service/browser/flows/login request_id=6c7316a8-7a55-4f05-a727-214d98ff8b4c

**Expected behavior**

Browser display form login

**Environment**

- Version: kratos image version latest-sqlite
- Environment: Ubuntu 20.04, Minikube

**Additional context**

**Comment by tnm0113** [comment]
It works fine if I set up dsn with a seperate Postgres deployment

**Comment by aeneasr** [comment]
Yeah, SQLite is not really a good idea to use here because SQLite generally has problems with concurrent connections. This means that you wouldn't be able to scale ORY Kratos at all. You'd also be managing database state on a persistent disk which is suboptimal.

We should probably disallow SQLite on disk.

To use the in-memory SQLite variant use `config.dsn=memory`. Keep in mind that all database state will be lost on a restart.

**Comment by aeneasr** [comment]
@tricky42 you've been working on ORY Kratos helm charts, maybe this is a good short spike for you? I think checking if `sqlite://` is prefixing in the DSN should be enough to make a decision wrt persistent volume.

**Comment by aeneasr** [comment]
I am closing this issue as it has not received any engagement from the community or maintainers in a long time. That does not imply that the issue has no merit. If you feel strongly about this issue

- open a PR referencing and resolving the issue;
- leave a comment on it and discuss ideas how you could contribute towards resolving it;
- open a new issue with updated details and a plan on resolving the issue.

We are cleaning up issues every now and then, primarily to keep the 4000+ issues in our backlog in check and to [prevent](https://www.jeffgeerling.com/blog/2020/saying-no-burnout-open-source-maintainer) [maintainer](https://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes) [burnout](https://docs.brew.sh/Maintainers-Avoiding-Burnout). Burnout in open source maintainership is a [widespread](https://opensource.guide/best-practices/#its-okay-to-hit-pause) and serious issue. It can lead to severe personal and health issues as well as [enabling catastrophic](https://haacked.com/archive/2019/05/28/maintainer-burnout/) [attack vectors](https://www.gradiant.org/en/blog/open-source-maintainer-burnout-as-an-attack-surface/).

Thank you to anyone who participated in the issue! 🙏✌️
