### ISSUE TITLE
oathkeeper: CustomResourceDefinition has openAPIV3Schema violation

### ISSUE THREAD

**Issue by karelbilek** [ory/k8s#163]
**Describe the bug**

the CustomResourceDefinition defined in oathkeeper-maester helm chart maybe has openapiv3 schema violation (I am not sure)

**To Reproduce**

* `minikube start`
* `helm install ory/oathkeeper --generate-name`
* `kubectl describe customresourcedefinition rules.oathkeeper.ory.sh | less`

You can see this in the back

```
    Message:               spec.versions[0].schema.openAPIV3Schema.properties[metadata]: Forbidden: must not specify anything other than name and generateName, but metadata is implicitly specified
    Reason:                Violations
```

the error is

> `spec.versions[0].schema.openAPIV3Schema.properties[metadata]: Forbidden: must not specify anything other than name and generateName, but metadata is implicitly specified`

**Expected behavior**

No violation

**Environment**

```
$ helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}
minikube - v1.12.2
kubernetes - 1.18.3
```

**Additional context**

I think this is a bug, not sure.

**Comment by karel-3d** [comment]
I think this is related to this

https://github.com/kubernetes/kubernetes/issues/80493

**Comment by karel-3d** [comment]
Oh, but it seems this error is actually "harmless".

**Comment by aeneasr** [comment]
Ok, should probably be fixed though!

**Comment by Demonsthere** [comment]
This should already be fixed by https://github.com/ory/k8s/pull/264
