### ISSUE TITLE
Kratos: add ability to add configmaps / volumes for identity schema

### ISSUE THREAD

**Issue by Ben-harder** [ory/k8s#166]
In the quickstart guide for Kratos, the identity schema is supplied via a file URL `default_schema_url: file:///etc/config/kratos/identity.traits.schema.json`. I would like to use this method through the helm charts but I cannot find a way to mount my schema file into the pod.

It would be great to have the ability to add configmaps and mount them to the pod such that schema URL's can point to files in the pod. 

As of right now, I have no idea of how to get around this, I don't know of a place where I can host the schema in my cluster so if there is an obvious solution, please suggest it!

[This](https://stackoverflow.com/questions/33415913/whats-the-best-way-to-share-mount-one-file-into-a-pod) is basically what I'm hoping for. Again, if there is a way to host the schema in my cluster and point the URL to that, any tips for doing that is appreciated. I haven't been able to find a reference for setting up Kratos to run in Kube using these charts.

Thanks!

**Comment by aeneasr** [comment]
Sounds like a great idea! Would you be open to contribute a change to make this possible? You can probably look at what oathkeeper does with the access rules.

**Comment by christian-roggia** [comment]
I believe that this issue has been solved? It is possible to add one or more json traits directly via Helm in Kratos.

https://github.com/ory/k8s/blob/master/helm/charts/kratos/templates/configmap-config.yaml#L14
https://github.com/ory/k8s/blob/master/helm/charts/kratos/values.yaml#L78

**Comment by aeneasr** [comment]
Yeah, it is possible. I think OP wants to mount additional config maps where those configs are set but that would be a manual process anyways, so I think it's ok to close this.
