### ISSUE TITLE
option to read dsn and other configs from secret/config->environment variables

### ISSUE THREAD

**Issue by azhang** [ory/k8s#181]
**Is your feature request related to a problem? Please describe.**

I think it's better to keep sensitive text such as DSN in a k8s secret rather than in a git-committed values.yaml

**Describe the solution you'd like**

have "env" options in the template values.yaml that can support secret and configmaps

**Additional context**

I am primarily using kratos

**Comment by aeneasr** [comment]
You can create a Kubernetes secret yourself and reference it instead of using the values.yml file, see here: https://github.com/ory/k8s/blob/master/helm/charts/kratos/values.yaml#L36-L40

**Comment by azhang** [comment]
ah I see. I was hoping I could read just the `dsn` from an existing secret (or env var), rather than writing the entire config into a secret. That way I can keep my dsn string in one place rather than having multiple secrets I have to sync manually.
