### ISSUE TITLE
Broken chart for the hydra maester rolebinding

### ISSUE THREAD

**Issue by alexivkin** [ory/k8s#225]
Specifying `--set 'hydra-maester.enabledNamespaces={<mynamespace>}` produces a broken definition:
`error validating data: ValidationError(RoleBinding.roleRef): unknown field "namespace" in io.k8s.api.rbac.v1.RoleRef; if you choose to ignore these errors, turn validation off with --validate=false`

**Comment by Demonsthere** [comment]
I think this can be closed as #262 was merged
