### ISSUE TITLE
enable hydra to run in nonPrivileged mode. 

### ISSUE THREAD

**Issue by Thilaknath** [ory/k8s#228]
**Is your feature request related to a problem? Please describe.**

Unable to run hydra when the cluster is set not to allow privileged containers.

**Describe the solution you'd like**

It would be good to have a securityContext as part of the deployment which could allow nonRootImages to be run. 
Example: https://github.com/ory/k8s/blob/master/helm/charts/keto/values.yaml#L31

The above is from the ketoProject

**Describe alternatives you've considered**

Please provide alternatives that could be considered. 

**Additional context**

**Comment by aeneasr** [comment]
Makes sense, contributions welcomed!
