### ISSUE TITLE
Feature extraVolumes not working

### ISSUE THREAD

**Issue by notsofunctional** [ory/k8s#230]
**Describe the bug**

I've tried to use the `extraVolumes` and `extraVolumeMounts` feature #220  and it seems to not output the list on the deployment (i've also copy pasted the values.yaml from here), this is the chunk of the values.yaml where i describe it:

![image](https://user-images.githubusercontent.com/3385668/110732722-51d25000-81ea-11eb-8ec6-29ebc6708719.png)

and this is the output:

![image](https://user-images.githubusercontent.com/3385668/110732958-bee5e580-81ea-11eb-883e-90e62ad986f6.png)

**To Reproduce**

Just try to use the `extraVolumes` and `extraVolumeMounts` field on values.yaml

**Expected behavior**

It expects to add the values from `extraVolumes` and `extraVolumeMounts` to deployment output

**Environment**

- Version: v0.5.3
- Environment: MacOS

**Additional context**

**Comment by zhming0** [comment]
I believe this feature hasn't been released yet. This feature was merged right after 0.5.3. 

I am personally waiting for this feature too and I believe it's a vital feature to have.

I chatted with the ORY team but they don't want to give a update schedule even just for this tiny helm repo. So the best option now is to wait or you can reach out to them too via Slack.

**Comment by aeneasr** [comment]
Right, made a release now. I guess we can close this now?

**Comment by zhming0** [comment]
Yes, it works on my deployment now. 

Really appreciate it @aeneasr 🙇 🙇

**Comment by aeneasr** [comment]
👍
