### ISSUE TITLE
Broken ory/hydra chart 

### ISSUE THREAD

**Issue by volvotrax** [ory/k8s#242]
Hello,

The ory/hydra chart produces a broken definition since the last commit 298eaabe8a89f77a1c28d787a033657a606d4024 yesterday. Cf.  PR https://github.com/ory/k8s/pull/237

`Error: YAML parse error on hydra/templates/deployment.yaml: error converting YAML to JSON: yaml: line 44: did not find expected '-' indicator`

I suspect this line to be badly formatted (bad indentation):
https://github.com/ory/k8s/blob/ae658964ca6e580ae1ae6ec6abc04ab232e06d35/helm/charts/hydra/templates/deployment.yaml#L62

I think it should be 
```
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "hydra.secretname" . }}
                  key: dsn
            {{- with .Values.deployment.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.deployment.securityContext | nindent 12 }}
```
instead of
```
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "hydra.secretname" . }}
                  key: dsn
            {{- with .Values.deployment.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            securityContext:
              {{- toYaml .Values.deployment.securityContext | nindent 12 }}
```

 By the way, the `securityContext` is already defined line 164.
Thanks

**Comment by Demonsthere** [comment]
Hi there @volvotrax and thanks for reporting it. You are right, one indent too far! Must have missed it :) 
The securityContext field is duplicated in `164` because, it's a per container setting

**Comment by volvotrax** [comment]
Thank you for your prompt fix!
