### ISSUE TITLE
Run migration containers as jobs not initContainer

### ISSUE THREAD

**Issue by aeneasr** [ory/k8s#247]
**Is your feature request related to a problem? Please describe.**

Because initContainer scale with the number of containers - meaning we get contestion for migrations. Instead, we should run a "run to completion once" container with exactly 1 pod (no concurrency)

**Comment by Demonsthere** [comment]
Possible solution:
- Single job with a CM mounted. In the CM we have some metadata (migration_occured, migration_date), which is set by the pod only if a migration was successful. 
- Deployments mount the CM and have an initJob that waits until the value in the CM is as expected (red light/green light)

**Comment by aeneasr** [comment]
Single job with CM sounds good!

**Comment by Demonsthere** [comment]
First draft, for now only hydra: https://github.com/ory/k8s/pull/248 will add the rest after some testing
