### ISSUE TITLE
Hydra maester helm open api schema not reflecting newest version

### ISSUE THREAD

**Issue by dennislemonmarkets** [ory/k8s#258]
**Describe the bug**

The version 0.6.1 (and up to the newest) of the hydra maester helm chart, should support v0.0.19 of the hydra maester. In this version the support for allowedCorsOrigins was added. Unfortunately the helm charts don't support this argument.

**To Reproduce**

1. Install helm hydra-maester >= v0.6.1
2. Try to create a client with attribute allowedCorsOrigins

**Expected behavior**

Client is created and allowed_cors_origins is saved to the hydra database. 
Actual behavior: client creation fails

**Additional context**
For me it looks like this can be fixed by adding allowCorsOrigins to the open api v3 schema: https://github.com/ory/k8s/blob/v0.6.1/helm/charts/hydra-maester/crds/crd-oauth2clients.yaml If so I am happy to help :)

**Comment by aeneasr** [comment]
Contributions to fix it greatly appreciated!

**Comment by Demonsthere** [comment]
Hello there. The CRD has been updated a few days ago in https://github.com/ory/k8s/pull/264 :) Could you verify if the issue persist in the newest version of the controller chart?
