### ISSUE TITLE
[oathkeeper-maester]: Outdated rule CRD

### ISSUE THREAD

**Issue by PeteMac88** [ory/k8s#263]
**Is your feature request related to a problem? Please describe.**

Problem is that the rules crds in the oathkeeper-maester helm chart are outdated.

**Describe the solution you'd like**

Please update the CRD to match the recent fix in this PR https://github.com/ory/oathkeeper-maester/issues/43

**Comment by Demonsthere** [comment]
Hello there. The CRD has been updated a few days ago in https://github.com/ory/k8s/pull/264 :)

**Comment by aeneasr** [comment]
Closing then :)
