### ISSUE TITLE
Add volumes support to Hydra migration job

### ISSUE THREAD

**Issue by ErwinSteffens** [ory/k8s#273]
**Is your feature request related to a problem? Please describe.**

The hydra auto migration job does not run because it cannot find the Postgres CA certificate.

**Describe the solution you'd like**

Add volumes support to Hydra migration job so we can add the Postgres CA certificate.

**Describe alternatives you've considered**

-

**Additional context**

The Kratos chart supports it already. See: https://github.com/ory/k8s/blob/master/helm/charts/kratos/templates/job-migration.yaml#L42

**Comment by aeneasr** [comment]
Merged!
