### ISSUE TITLE
Upgrade default Kratos version to 0.6: a few challenges & options

### ISSUE THREAD

**Issue by zhming0** [ory/k8s#285]
**Is your feature request related to a problem? Please describe.**

Currently, there are a few problems with the Kratos Chart. 

1. Default Kratos image is still v0.5. 
2. Default Kratos image use the SQLite version. 
3. If user overrides the image tag to v0.6, the user has no way to spin up the `courier`, neither for the singleton setup nor the multi-instance setup.

Therefore, there is some work needed to be done for the v0.6 upgrade. 

**Describe the solution you'd like**

Introduce a new singleton `courier` deployment. 

There are a few viable options for this chart upgrade:

1. [Recommended] Change the default tag to use non-sqlite version `v0.6.3-alpha.1`, allow user opting out the courier deployment, and opt in the `--watch-courier` option. 
    * Pro: fits most users' workflow. 
2. Keep the current tradition, change the default tag to `v0.6.3-alpha.1-sqlite`, allow user to opt-in the courier deployment option. 
    * Pros: Backward compatible.
3. [Best long term] Reconsider the necessity of `kratos courier watch`, a DB transaction-based solution might be an alternative option to avoid the race condition of multiple couriers.
    * Pros: no need for the `courier` deployment. Simpler. Scalable.
    * Cons: depending on DB and implementation, might incur small performance penalty
    
    
I am happy to help.  Keen to know your thoughts

**Comment by aeneasr** [comment]
In our system we are using a StatefulSet for the courier watcher which allows us to run it as a long-running process but also be able to up/downgrade it. We haven't ported that to the open source yet though.

Generally, I think we should probably disable `--watch-courier` in kubernetes as most people probably run it with a replication factor > 1. I think supporting SQLite still makes sense though, you could write the DB to a PVC which would be a minimalistic zero-dependency but yet still working deployment!

**Comment by zhming0** [comment]
Cool, I think we are on the same page. We will make `--watch-courier` opt-in for people who wants to use SQLite. 

Meanwhile, @aeneasr do you mind approving #286 for now? It offers a quick temporary path for people (like me) wanting to deploy 0.6 to prod. 

---

Lastly, I am still a bit unsure why the courier worker has to be a singleton. I understand we use DB as a task queue, and this should allow parallel processing. Is there a particular reason we want it to be singleton? Like strictly FIFO?

**Comment by aeneasr** [comment]
> Lastly, I am still a bit unsure why the courier worker has to be a singleton. I understand we use DB as a task queue, and this should allow parallel processing. Is there a particular reason we want it to be singleton? Like strictly FIFO?

We don't do row / table locking so some mails would be sent twice if you have multiple workers running!

**Comment by aeneasr** [comment]
@Demonsthere maybe you could help to port the kratos helm chart we have in cloud to OSS?

**Comment by zhming0** [comment]
@aeneasr I have gave it a quick stab in #289. Sorry it's relatively a big PR. 

Keen to know how you guys setup the StatefulSet in cloud.

**Comment by Demonsthere** [comment]
I have ported over the changes we have made in https://github.com/ory/k8s/pull/290. @zhming0 how about you take a look there, and maybe we can merge your customisations into it :)?
