### ISSUE TITLE
Issue with hydra.dangerousAllowInsecureRedirectUrls

### ISSUE THREAD

**Issue by chriskolenko** [ory/k8s#29]
**Describe the bug**

hydra.dangerousAllowInsecureRedirectUrls isn't implemented correctly

**To Reproduce**

**Expected behavior**

It should install with the correct args passed through to the container.

**Environment**

N/A

**Additional context**

Find the problem here:
https://github.com/ory/k8s/blob/master/helm/charts/hydra/templates/deployment.yaml#L57-L62

Not sure if hydra takes multiple key pairs of ""--dangerous-allow-insecure-redirect-urls" or if the value should be comma separated.

**Comment by aeneasr** [comment]
Ah yeah that should be comma separated. Would you be up for a PR? :)
