### ISSUE TITLE
oathkeeper-maester.getCM fails when release name contains hyphens

### ISSUE THREAD

**Issue by tgaddair** [ory/k8s#294]
**Describe the bug**

For Oathkeeper Maester in `_helpers.tpl`, the function `oathkeeper-maester.getCM` will not work correctly if the release name contains a hyphen `-`.

Specifically, the split done here: https://github.com/ory/k8s/blob/master/helm/charts/oathkeeper-maester/templates/_helpers.tpl#L55 will fail for releases named something like `foo-bar`, creating a full name like `foo-bar-oathkeeper` as the split will only consider the first two parts.

The resulting config map will be named: `foo-bar-rules`, but Oathkeeper will expect `foo-bar-oathkeeper-rules`.

**To Reproduce**

Install oathkeeper maester with a release name containing hyphens.

**Expected behavior**

The config map name should be consistent with Oathkeeper.

**Environment**

- Version: v0.15.1
- Environment: K8s

**Comment by aeneasr** [comment]
Nice find, contribs welcomed!
