### ISSUE TITLE
Update the Ingress objects for all charts 

### ISSUE THREAD

**Issue by Demonsthere** [ory/k8s#305]
**Is your feature request related to a problem? Please describe.**

In #299 we have updated the Ingress definition to be compliant with newest version of k8s and noticed that the manifests differs between charts (for example compare [oathkeeper](https://github.com/ory/k8s/blob/master/helm/charts/oathkeeper/templates/ingress-api.yaml#L3) and [keto](https://github.com/ory/k8s/blob/master/helm/charts/keto/templates/ingress-write.yaml#L3)). 

**Describe the solution you'd like**

Update all charts to have the same Ingress definition using the current version of k8s (1.18+)

**Describe alternatives you've considered**

A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

This is a breaking change, as the charts will no longer work on older version of k8s (< 1.18). This however should not be a big issue, as that version of k8s is already EOL

- Followup to https://github.com/ory/k8s/pull/299

**Comment by piotrmsc** [comment]
Once this is finished and released we need to make sure it is mentioned (dropping support for k8s <1.18) on the release itself as kind of release note

**Comment by Demonsthere** [comment]
Yeah, and in the readme of each release we need to include the upgrade steps requires, so we can link them in the Release notes
