### ISSUE TITLE
Kratos deployment yaml creates a pod which does not use mysql dialect

### ISSUE THREAD

**Issue by sjmittal** [ory/k8s#312]
**Describe the bug**
I am using kratos version `v0.7.1-alpha.1`. I am trying to deploy kratos on k8s using the yaml provided by the  helm charts. I have configured the chart with mysql dsn: `mysql://user:secret@tcp(mysqld:3306)/database`
However when applying the yaml it seems to use sqlite3 dialect when trying to create the schema.

**To Reproduce**
Apply the deployment yaml with mysql as dsn.

In pod created fails with repeated errors like:
`{"audience":"application","level":"debug","msg":"Ignoring migration file 20210618103120000013_logout_token.sqlite3.up.sql because dialect is not supported: unsupported dialect sqlite3","service_name":"Ory Kratos","service_version":"v0.7.1-alpha.1","time":"2021-08-16T06:32:31Z"}`

Is this the issue with k8s configuration or some bug within kratos?

**Comment by aeneasr** [comment]
Thank you for contributing to this repository by creating an issue!

Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.

Please also ensure that your issue is appropriately formatted. If you do not know how to write markdown, you can find help [here](https://guides.github.com/features/mastering-markdown/).

Helping you with your problem is only possible if you share this information, and it will save a lot of time of back and forth on your as well as our end!

For this reason, this repository uses [issue templates](../tree/master/.github/ISSUE_TEMPLATE) which you can select when pressing "New issue". Please use one of those issue templates to fill in the required information. You can either create a new issue for this purpose and close this one, or leave a comment.

If you have used an issue template and see this comment, it means that your description lacks information that allows maintainers to understand what problem you are facing and how to reproduce it.

> Do not edit the original post as we will not be notified when you do so.

If you do not provide the requested information, this issue will be closed. Thank you for your understanding!

---

In particular: your config is missing, your helm version is missing, your k8s version is missing, …

**Comment by sjmittal** [comment]
**Describe the bug**

Kratos is using sqlite3 dialect instead of mysql when mysql connection is provided in dsn.

**To Reproduce**

Steps to reproduce the behavior:

1. Modify the dsn variable to use: `mysql://user:secret@tcp(mysqld:3306)/database`
2. Apply the generated yaml to k8s cluster

**Expected behavior**

Kratos pod should use mysql connection to create the schema

**Environment**

- AWS EKS cluster.

**Additional context**

It uses sqlite and is unable to apply the schema to mysql with error message:

`{"audience":"application","level":"debug","msg":"Ignoring migration file 20210618103120000013_logout_token.sqlite3.up.sql because dialect is not supported: unsupported dialect sqlite3","service_name":"Ory Kratos","service_version":"v0.7.1-alpha.1","time":"2021-08-16T06:32:31Z"}`

**Comment by aeneasr** [comment]
> your config is missing

POlease include your full helm config

**Comment by sjmittal** [comment]
Please find the output of dry run for help chart:
https://pastebin.pl/view/1ee59d86

**Comment by aeneasr** [comment]
The log file you are referring to can be ignored. It is just debug information.

**Comment by sjmittal** [comment]
No, but the pod is not in running state. Due to that bug looks like schema is not getting created:
```
{"audience":"application","level":"debug","msg":"Ignoring migration file 20210618103120000013_logout_token.sqlite3.up.sql because dialect is not supported: unsupported dialect sqlite3","service_name":"Ory Kratos","service_version":"v0.7.1-alpha.1","time":"2021-08-16T13:34:42Z"}
{"audience":"application","error":{"message":"mysql select one: Error 1146: Table 'kratosdb_68cbce5a.networks' doesn't exist","trace":"\ngithub.com/ory/x/sqlcon.HandleError\n\t/go/pkg/mod/github.com/ory/x@v0.0.262/sqlcon/error.go:88\ngithub.com/ory/x/networkx.(*Manager).Determine\n\t/go/pkg/mod/github.com/ory/x@v0.0.262/networkx/manager.go:42\ngithub.com/ory/kratos/persistence/sql.(*Persister).DetermineNetwork\n\t/home/ory/persistence/sql/persister.go:77\ngithub.com/ory/kratos/driver.(*RegistryDefault).Init.func1\n\t/home/ory/driver/registry_default.go:535\ngithub.com/cenkalti/backoff.RetryNotify\n\t/go/pkg/mod/github.com/cenkalti/backoff@v2.2.1+incompatible/retry.go:37\ngithub.com/cenkalti/backoff.Retry\n\t/go/pkg/mod/github.com/cenkalti/backoff@v2.2.1+incompatible/retry.go:24\ngithub.com/ory/kratos/driver.(*RegistryDefault).Init\n\t/home/ory/driver/registry_default.go:475\ngithub.com/ory/kratos/driver.New\n\t/home/ory/driver/factory.go:14\ngithub.com/ory/kratos/cmd/serve.NewServeCmd.func1\n\t/home/ory/cmd/serve/root.go:33\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897\ngithub.com/ory/kratos/cmd.Execute\n\t/home/ory/cmd/root.go:48\nmain.main\n\t/home/ory/main.go:35\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"},"level":"warning","msg":"Unable to determine network, retrying.","service_name":"Ory Kratos","service_version":"v0.7.1-alpha.1","time":"2021-08-16T13:34:42Z"}```

I guess schema should be created when starting the kratos pod, but looks like it does not as it is trying to use sqlite3

**Comment by Demonsthere** [comment]
Hello there!
We provide 2 flavours of the kratos image: `oryd/kratos:v0.7.1` and `oryd/kratos:v0.7.1-sqlite`. You can override which image is used with the helm variables (see [values.yaml](https://github.com/ory/k8s/blob/master/helm/charts/kratos/values.yaml#L13)). Could you verify if the problem exists in the sqlite flavour?

**Comment by sjmittal** [comment]
> 
> 
> Hello there!
> We provide 2 flavours of the kratos image: `oryd/kratos:v0.7.1` and `oryd/kratos:v0.7.1-sqlite`. You can override which image is used with the helm variables (see [values.yaml](https://github.com/ory/k8s/blob/master/helm/charts/kratos/values.yaml#L13)). Could you verify if the problem exists in the sqlite flavour?

It is working with `oryd/kratos:v0.7.1`. Issue was that I had not applied the auto migration chart but now I applied that it is fixed.

**Comment by Demonsthere** [comment]
Good to hear that it works :) If so, I think we can close this. Please reopen, if you need any more assistance.
