### ISSUE TITLE
Charts Should Be Compatible With HPA

### ISSUE THREAD

**Issue by samcgardner** [ory/k8s#318]
**Is your feature request related to a problem? Please describe.**

It's currently impossible to use the deployments in these charts alongside the HPA in a GitOps setup, since you are forced to specify the `replicas` value. This means that any changes the HPA makes will be immediately reversed by the GitOps agent. 

EDIT: 

Minor addendum - Keto doesn't suffer from this issue since it ships its own HPA and correctly removes the `replicas` field from the deployment template if it is configured.

**Describe the solution you'd like**

Change the deployment templates like so to make the `replicas` value optional:

```yaml
{{ if  .values.replicaCount }}
  replicas: {{ .Values.replicaCount }}
{{ end }}
```

**Describe alternatives you've considered**

I don't see another plausible solution to this problem.

**Additional context**

I'm happy to PR this if you're willing to review.

**Comment by piotrmsc** [comment]
I reproduced the original issue easily on local env with : 
```
k3d create cluster test

argocd app create hydra --repo https://github.com/ory/k8s.git --path helm/charts/hydra  --dest-server https://kubernetes.default.svc --dest-namespace default --helm-set hydra.config.secrets.system={SOME_SECRET} --helm-set hydra.config.dsn=memory --helm-set hydra.config.urls.self.issuer=https://my-hydra/ --helm-set hydra.config.urls.login=https://my-idp/login --helm-set maester.enabled=false --helm-set image.tag=v1.10.5-sqlite --helm-set deployment.autoscaling.enabled=true --helm-set deployment.autoscaling.minReplicas=2 --helm-set deployment.autoscaling.maxReplicas=3 --helm-set deployment.autoscaling.targetCPUUtilizationPercentage=2 --helm-set deployment.resources.requests.cpu=10m --sync-policy auto --self-heal

```
