### ISSUE TITLE
Multiple config files

### ISSUE THREAD

**Issue by MatthieuCoder** [ory/k8s#332]
**Is your feature request related to a problem? Please describe.**

I'm trying to run Hydra in Kubernetes using Vault as a DSN provider; for other containers i just change the startup script and load the environment variables using `source`, but the hydra container does not includes sh

**Describe the solution you'd like**

I'm thinking about multiple config files (like docker-compose does), so I can load another file from vault containing the secret

**Describe alternatives you've considered**

Loading secrets from files could be another solution, but this seems over complicated compared to the first solution

**Comment by MatthieuCoder** [comment]
I'll look into that. I'll send a pr if it's not possible

**Comment by MatthieuCoder** [comment]
Actually, for it to work, I need to be able to disable the configmap (or the DSN will be overwritten py the environment variable)

**Comment by Demonsthere** [comment]
Hi there, I think that actually the chart supports everything you might need for this to work:
- [Use custom secret for hydra](https://github.com/ory/k8s/blob/master/helm/charts/hydra/values.yaml#L125)
- Mount additional config files [as extraVolumes](https://github.com/ory/k8s/blob/master/helm/charts/hydra/values.yaml#L223)
- The only thing that is missing is the expansion of [arguments for the container](https://github.com/ory/k8s/blob/master/helm/charts/hydra/templates/deployment.yaml) but that shouldn't be hard to achieve. 

If you can verify if the first 2 points are enough, I can patch the 3rd one quite easily ;)

**Comment by MatthieuCoder** [comment]
The first one does not work, the vault operator uses a sidecar container to create files on a shared volume between the two containers. The second solution may work using the vault csi provider, but we still need to configure hydra to load the file on the new volume (this might require to store the configuration file directly, so no compatibility with the vault system for managing database access)

The last solution might be enough considering we can already have the vault agent sidecar running with their mutating webhook, we could load an additional configuration file generated by the vault sidecar.
The last thing i might need is to disable the secret generated by the chart, because as i understand it, it will override the configuration file (and the additional configuration file)

**Comment by Demonsthere** [comment]
I see. I guess the simples solution will be to port the same mechanism of optional secret as we have in [keto](https://github.com/ory/k8s/blob/master/helm/charts/keto/values.yaml#L97)

**Comment by MatthieuCoder** [comment]
I see... I'll use (ExternalSecret)[https://github.com/external-secrets/kubernetes-external-secrets] then
