### ISSUE TITLE
Don't enforce DSN in secret

### ISSUE THREAD

**Issue by toonvanstrijp** [ory/k8s#353]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Right now a lot of ory products use a DSN to connect with the database. This is fine, however it's causing configuration issues when you want to use a existing secret that only contains the username and password for example.

### Describe your ideal solution

The ideal solution would be to modify the helm chart so that it doesn't enforce the DSN. This way we could set it manually and have more control over how this DSN is provided.

### Workarounds or alternatives

The current workaround involves creating the DSN secret beforehand or with a initContainer or job.

### Version

v0.20.0

**Comment by MOZGIII** [comment]
The most flexible way is to simply allow omitting the DSN, and letting the user to pass it via `extraEnv`
