### ISSUE TITLE
Deploy Hydra in k8s failed

### ISSUE THREAD

**Issue by Emin3mU** [ory/k8s#369]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

hydra's status is CrashLoopBackOff. 
exec "kubectl logs hydra", get this msg
```
time=2021-11-18T08:06:16Z level=info msg=No tracer configured - skipping tracing setup audience=application service_name=ORY Hydra service_version=v1.9.2
time=2021-11-18T08:06:16Z level=fatal msg=Could not ensure that signing keys for "hydra.openid.id-token" exists. If you are running against a persistent SQL database this is most likely because your "secrets.system" ("SECRETS_SYSTEM" environment variable) is not set or changed. When running with an SQL database backend you need to make sure that the secret is set and stays the same, unless when doing key rotation. This may also happen when you forget to run "hydra migrate sql".. audience=application error=map[message:cipher: message authentication failed] service_name=ORY Hydra service_version=v1.9.2
```

### Reproducing the bug

hydra pod yaml
[hydra_yaml.txt](https://github.com/ory/hydra/files/7561208/hydra_yaml.txt)

### Relevant log output

exec "kubectl get secret -n plc"

kubectl get secret -n plc
NAME                                      TYPE                                  DATA   AGE
pl-hydra-secrets                          Opaque                                3      51m

### Version

v1.9.2-sqlite

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes

**Comment by Demonsthere** [comment]
Hey @Emin3mU can you give some more context here? Was that a clean installation? An update? The logs suggest that:
- In an install scenario, you didn't use the autoMigrate job
- In an upgrade scenario, the secrets you supplies didn't match those that were in the db

**Comment by Emin3mU** [comment]
@Demonsthere  Thanks for your reply. This is an attempt to install in the namespace plc，but it failed several times before that，and i deleted the namespace.
This is [hydra_deploment](https://github.com/ory/k8s/files/7567118/hydra_deploment.txt) 
create secret command: 
```
kubectl create secret generic -n "${namespace}" \
  pl-hydra-secrets \
  --from-literal=SECRETS_SYSTEM="$(LANG=C; < /dev/urandom tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1)" \
  --from-literal=OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT="$(LANG=C; < /dev/urandom tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1)" \
  --from-literal=CLIENT_SECRET="$(LANG=C; < /dev/urandom tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1)"
```
get secret:
```
#kubectl get secret -n plc pl-hydra-secrets -o yaml
apiVersion: v1
data:
  CLIENT_SECRET: ZFloaHZqcjJrOVlqcHFEbVNRa1hralAxVzZHZzVnNjJlQlFZMEJGa044S3Eycms4YnQ0amxZT2NEVTM4UjA3bw==
  OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT: OEl4bEMxTnNOU25qcEtQTWdQMHdoSGRLZnZ0QzJFN00xZUgzbG1SVGs4VmtzMXE3bmRyclBLdXpYS3EzQUw5UQ==
  SECRETS_SYSTEM: Y09OTjZlRWdqMEpEMzczRnVjMWZOMkdBcnQwUWZLYzBQYWdDY21PenVQS01UQW00bnl2VXE5aUZ5VG1ydG1IYQ==
kind: Secret
metadata:
  creationTimestamp: "2021-11-18T07:17:08Z"
  name: pl-hydra-secrets
  namespace: plc
  resourceVersion: "2038699"
  uid: eb11f77c-a8e4-43fd-a1ce-42d3b049d165
type: Opaque
```

**Comment by Emin3mU** [comment]
I delete the dirty data of the postgres,it works
