### ISSUE TITLE
Issue scaling kratos in kubernetes

### ISSUE THREAD

**Issue by dan2kx** [ory/k8s#373]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I'm having issues scaling a kratos container in Kubernetes using the helm chart, it seems that when I go above one container it doesn't maintain my user state/sessions between the containers, is there something I need to configure for this to work?
5 replies

### Reproducing the bug

Install kratos using helm and the latest chart (0.21, originally noticed the issue in the 0.19 chart) set replicants to 2 or more

try to login on connected self-service app, the connection is routing between the containers as expected but the user state is not - so the user sees a login screen over and over.

This is not an issue if only one container is used. 

The container logs show 403 forbidden, as if the cookie is unknown the alternative server

### Relevant log output

```shell
{"audience":"application","error":{"debug":"","message":"The requested action was forbidden","reason":"Please include a valid session cookie or session token when calling this endpoint.","status":"Forbidden","status_code":403} //...
{"audience":"application","error":{"debug":"","message":"The requested action was forbidden","reason":"Please include a valid session cookie or session token when calling this endpoint.","status":"Forbidden","status_code":403} //...
{"audience":"application","error":{"debug":"","message":"The request could not be authorized","reason":"A valid Ory Session Cookie or Ory Session Token is missing.","status":"Unauthorized","status_code":401} //...
{"audience":"application","error":{"debug":"","message":"The requested action was forbidden","reason":"Please include a valid session cookie or session token when calling this endpoint.","status":"Forbidden"} //...
{"audience":"application","error":{"debug":"","message":"The request could not be authorized","reason":"A valid Ory Session Cookie or Ory Session Token is missing.","status":"Unauthorized","status_code":401} //...
```

### Version

0.21.0

### On which operating system are you observing this issue?

Other

### In which environment are you deploying?

Kubernetes with Helm

**Comment by tricky42** [comment]
Hi @dan2kx, 

my guess would be that you use Kratos with no external datasource configured. Without specifying a `dsn` pointing to a support database Kratos will use SQLite. As SQLlite is running in the Kratos container storing the data in memory in your case you are essentially running two independent instances and the two Kratos instances are not accepting the Session Cookies etc of the other instances. 

So in order to fix your setup you would have to deploy one of the supported databases to the cluster or use a database service like AWS RDS or GCP Cloud SQL and configure a DSN to point to this instance (and therefore all Kratos instances using the same DB).

Does this fix your problem?

**Comment by dan2kx** [comment]
Hi @tricky42 thanks for getting back to me, 

Sorry i forgot to mention i am using a mysql dsn which is set in my values file, i'm also setting the session secret

```
kratos:
  config:
    dsn: mysql://xxxx
    secrets:
      session:
        - xxxx
```

**Comment by tricky42** [comment]
Hmmm, can you check if the config really got applied by checking the content of the `kratos` secret? This should contain the `dsn` configured in your `values.yaml`.

**Comment by dan2kx** [comment]
i can see the kratos secret is there with the following keys:
- dsn
- secretsCookie
- secretsDefault
- smtpConnectionURI

i can also see the `DSN` environment variable is being used by the container as well as the `COURIER_SMTP_CONNECTION_URI` which are correct. Interestingly i don't see the secrets listed here though, is that an issue?

**Comment by Demonsthere** [comment]
Hi @dan2kx the secrets should be loaded as Envs into the pod. If they are not present, this will cause problems, as the instance will not be able to connect to the DB

**Comment by dan2kx** [comment]
Does that mean there is a problem with the chart or my configuration?

**Comment by dan2kx** [comment]
I was reviewing the charts and i think i see the issue, the documentation [here](http://k8s.ory.sh/helm/kratos.html) says to use the the key `session` but it should actually be `default`

**Comment by Demonsthere** [comment]
We currently support 2 ways of providing the secrets:
- Passing them as values during installation
- Providing a pre-loaded secret object, which has the required data. This has been recently patched in https://github.com/ory/k8s/issues/349
