### ISSUE TITLE
Change kratos ConfigMap to kind Secret

### ISSUE THREAD

**Issue by jceb** [ory/k8s#386]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

I noticed that `kratos-config` is of kind `ConfigMap` but it contains potentially sensitive information like the oidc provider configuration.

### Describe your ideal solution

I propose to change the whole configuration to kind `Secret`. This allows for other mechanisms like SOPS secrets encryption for gitops purposes to be applied as well.

### Workarounds or alternatives

Manual patching of kubernetes resources via kustomize.

### Version

0.8.2-alpha.1

**Comment by Demonsthere** [comment]
Hello there!
For clarification, the current mechanism supports both ConfigMaps and Secrets, although in a less than straightforward manner. All of Ory applications support config via both, file and env variables, where the latter take priority. We strongly encourage users to supply sensitive information via a [custom secret](https://github.com/ory/k8s/blob/master/helm/charts/kratos/values.yaml#L54) and loading the values from the secret [as envs](https://github.com/ory/k8s/blob/master/helm/charts/kratos/values.yaml#L186)

**Comment by jceb** [comment]
Thanks, I just learned about the `deployment.extraVolumes` and `deployment.extraVolumeMounts` options in `values.yaml`. It all works very well. Thank you!
