### ISSUE TITLE
Missing flow control for some optional parts in Oathkeeper and Oathkeeper Maester chart templates

### ISSUE THREAD

**Issue by devopyos** [ory/k8s#400]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

It seems that some blocks in chart templates should be wrapped in `if` statements.

Creating helm release without declaring `annotations` in values leads to a somewhat misleading render: helm outputs resource definitions with `annotations` key that has no value, which is replaced with an empty map after deploy.

The same applies to `NodeSelector` in Maester chart. Again, rendering templates without declaring anything for `NodeSelector` results in manifest with `NodeSelector` key that has no value.

Also, there is `deployment.extraEnv` in Oathkeeper chart. This block is a bit different and might be a corner case, but I'll describe the scenario just in case.

You'll get empty `env` key  in pods spec with he following setup:
  - `deployment.extraEnv` is an empty list
  - datadog is disabled
  - `oathkeeper.mutatorIdTokenJWKs` is not set

### Describe your ideal solution

I guess templates should have such blocks wrapped in `if` statements ([example](https://github.com/jaegertracing/helm-charts/blob/7a677407302e667258fb711de38a91ee6b922a1a/charts/jaeger/templates/query-deploy.yaml#L9)). It's seems to be more friendly and more obvious solution.

### Workarounds or alternatives

Keep everything as it is?

### Version

oathkeeper helm chart version 0.21.8

### Additional Context

Can contribute to this

**Comment by Demonsthere** [comment]
Interesting, an empty array/object should not fail the deployment as those are allowed by the k8s api. Need to investigate this

**Comment by devopyos** [comment]
@Demonsthere yes, you're right. My bad, I've missed that the resource definition is still valid. Sorry.
Should I close this issue in favor of a new one, that will be a feature request?

**Comment by Demonsthere** [comment]
No need, pease update this issue to be a Feature Request :)

**Comment by devopyos** [comment]
@Demonsthere done! Thanks!
I'll try to make PR as soon as I'll have time
