### ISSUE TITLE
Allow disabling securityContext

### ISSUE THREAD

**Issue by fraxachun** [ory/k8s#421]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

In some environments (e.g. OpenShift) you might want not to set the securityContext. Due to this behaviour of helm (https://github.com/helm/helm/issues/9136) it is not possible to unset the securityContext via own values. Also workarounds like setting the securityContext to false don't work.

### Describe your ideal solution

Add a value deployment.securityContext.enabled which allows to omit setting the securityContext. This is how the securityContext could be applied:

```
          {{- if .Values.deployment.securityContext.enabled }}
          securityContext: {{- omit .Values.deployment.securityContext "enabled" | toYaml | nindent 10 }}
          {{- end }}
```

### Workarounds or alternatives

I couldn't find any alternative to the above suggestion.

### Version

0.22.2

**Comment by fraxachun** [comment]
See https://github.com/ory/k8s/pull/422

**Comment by Demonsthere** [comment]
Closing as #422 was merged
