### ISSUE TITLE
Warning when setting extraInitContainers in Kratos chart: coalesce.go:200: warning: cannot overwrite table with non table for extraInitContainers (map[])

### ISSUE THREAD

**Issue by drigz** [ory/k8s#424]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When setting deployment.extraInitContainers in the Kratos Helm chart and using `helm template`, you get a warning that sounds like an error: `cannot overwrite table with non table for kratos.deployment.extraInitContainers`.

This is because values.yaml specifies an empty object (the commented example there won't work either);

```
  # -- If you want to add extra init containers. These are processed before the migration init container.
  extraInitContainers: {}
  # extraInitContainers: |
  #  - name: ...
  #    image: ...
```

https://github.com/ory/k8s/blob/b9c76ecc08b3fd6ccf859c0bc800a10da425c3f8/helm/charts/kratos/values.yaml#L214

But the templates pass this to `tpl` which expects a string (although it seems to cope with an empty object, but rejects non-empty objects with `wrong value for type`):

```
    {{- if .Values.deployment.extraInitContainers}}
      initContainers:
        {{- if .Values.deployment.extraInitContainers }}
{{ tpl .Values.deployment.extraInitContainers . | indent 8 }}
        {{- end }}
    {{- end }}
```

https://github.com/ory/k8s/blob/master/helm/charts/kratos/templates/deployment.yaml#L46 (not sure about the duplicated `if` either)

I'd expect this to be fixed simply by replacing `{}` in values.yaml with `""`.

### Reproducing the bug

```
$ helm3 version
version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}
$ helm3 template kratos ory/kratos --version 0.22.2 --set deployment.extraInitContainers="- name: foo" > /dev/null        
coalesce.go:220: warning: cannot overwrite table with non table for kratos.deployment.extraInitContainers (map[])
```

### Version

0.22.2

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm

### Additional Context

I would send a PR but I have to discuss the CLA with my employer first, could take some time.

**Comment by fokoenecke** [comment]
I am able to set the value. It expects a template string. You have to use the underlying [tpl function](https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function) to build the container object yourself, I guess.

**Comment by drigz** [comment]
Can you share how you're setting it and maybe which version of the chart and Helm you're using? I can't set a string:

```
$ helm template kratos ory/kratos --version 0.22.2 --set-string deployment.extraInitContainers="[]" > /dev/null
coalesce.go:220: warning: cannot overwrite table with non table for kratos.deployment.extraInitContainers (map[])
```

**Comment by fokoenecke** [comment]
oh, yeah - sorry.
that's because you have to escape almost everything when using `--set`
`--set '\{\{print\ "#hello world"\}\}'` works for me.

I agree, that you should use a `values.yaml`. I think you need to reference your container array in the template key (`extraInitContainers`).
```
containers: |
  - name: foo
    image: busybox

extraInitContainers: "{{ .Values.containers }}"
```

**Comment by drigz** [comment]
I still see the error with these examples, if I fix them to refer to deployment.extraInitContainers:

```
$ helm version
version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}
$ cat values_indirect.yaml 
containers: |
  - name: foo
    image: busybox

deployment:
  extraInitContainers: "{{ .Values.containers }}"
$ helm template kratos ory/kratos --version 0.22.2 --values values_indirect.yaml > /dev/null
coalesce.go:220: warning: cannot overwrite table with non table for kratos.deployment.extraInitContainers (map[])
$ helm template kratos ory/kratos --version 0.22.2 --set '\{\{print\ "#hello world"\}\}' > /dev/null
Error: failed parsing --set data: key "{{print \"#hello world\"}}" has no value
$ helm template kratos ory/kratos --version 0.22.2 --set 'deployment.extraInitContainers=\{\{print\ "#hello world"\}\}' > /dev/null
coalesce.go:220: warning: cannot overwrite table with non table for kratos.deployment.extraInitContainers (map[])
```

**Comment by fokoenecke** [comment]
```
$ helm version
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"archive", BuildDate:"2022-02-18T22:31:12Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9+rke2r1", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T21:17:19Z", GoVersion:"go1.16.12b7", Compiler:"gc", Platform:"linux/amd64"}
```
I just downloaded the ory/k8s sources of Release 0.22.2 (and also current master) and did this:
```
$ helm install --dry-run --debug --values ./values.yaml kratos ./k8s-0.22.2/helm/charts/kratos
```
with this as `values.yaml`:
```
containers: |
  - name: foo
    image: busybox

deployment:
  extraInitContainers: "{{ .Values.containers }}"

```
and it worked
```
---
# Source: kratos/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kratos
  namespace: classpad-prod
  labels:
    app.kubernetes.io/name: kratos
    helm.sh/chart: kratos-0.22.2
    app.kubernetes.io/instance: kratos
    app.kubernetes.io/version: "v0.9.0-alpha.2"
    app.kubernetes.io/managed-by: Helm
...
...
    spec:
      initContainers:
        - name: foo
          image: busybox
        
      volumes:
        - name: kratos-config-volume
...
...
---
```

then this I tried this with the same result:
```
$ helm template --version 0.22.2 --values ./values.yaml kratos ory/kratos
```

**Comment by Demonsthere** [comment]
Hello there!
You are correct, this is only a warning, as `initContainers` is defined as an array, and we are technically passing a multiline string there, which then is converted into a yaml array format. 
This may seen error prone, but as showed by @fokoenecke allows you to use other values within the code (which is very useful, as you can copy labels, envs, or other fields inside). 
I think that this would benefit from a better documentation, and would for sure appreciate a PR describing the problem/solution 😉
