### ISSUE TITLE
add nodeSelector for migration jobs

### ISSUE THREAD

**Issue by fokoenecke** [ory/k8s#425]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

The nodes in our kubernetes cluster as restricted on which external servers they may connect to. Thus we heavily rely on nodeSelectors to ensure our services are able to access resources like databases. Unfortunately I could not find a way to add a node selector [kratos](https://github.com/ory/k8s/blob/master/helm/charts/kratos/templates/job-migration.yaml) and [hydra](https://github.com/ory/k8s/blob/master/helm/charts/hydra/templates/job-migration.yaml) migration job yamls.

The same applies to kratos-courier and maybe other parts I don't know about.

### Describe your ideal solution

If the job templates had a section
```
{{- with .Values.job.nodeSelector }}
  nodeSelector: {{- . | toYaml | nindent 8 }}
{{- end }}
```
I would be able to set a nodeSelector via `--set job.nodeSelector.my/label=value`

### Workarounds or alternatives

I thought about extending the charts somehow or finding other ways to modify the scheduler, but couldn't find a way, yet.
edit: I ended up downloading the chart, modify it and deploy from local. but that's bad, obviously.

### Version

v0.21.5 kratos / v0.21.5  hydra

**Comment by Demonsthere** [comment]
Hi there, I agree, we would need to update the charts globally and include the new options in all of them. Like always all contributions are welcome 😉
