### ISSUE TITLE
Published Kratos Helm chart not updated to v0.9

### ISSUE THREAD

**Issue by aran** [ory/k8s#426]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The Ory Kratos helm chart at https://k8s.ory.sh/helm/charts/index.yaml is showing `appVersion: v0.8.0-alpha.3` but it appears the latest is `v0.9.0-alpha.2`

### Reproducing the bug

Visit https://github.com/ory/k8s/blob/master/docs/helm/charts/index.yaml

### Version

v0.8.0-alpha.3

### In which environment are you deploying?

Kubernetes with Helm

**Comment by Demonsthere** [comment]
Hi there!
That is because the charts follow the main applications, and are not auto upgraded to the newest release 😉 . I have just released [0.23.0](https://github.com/ory/k8s/releases/tag/v0.23.0) which bumps kratos

**Comment by Demonsthere** [comment]
Ok, the pipeline problems have been fixed, and 0.23.0 released, enjoy your out of the box kratos 😉
