### ISSUE TITLE
Error: INSTALLATION FAILED: failed to download "ory/hydra"

### ISSUE THREAD

**Issue by hongbo-miao** [ory/k8s#429]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I am trying to install Ory Hydra on a local Kubernetes created by [k3d](https://k3d.io/) using Helm based on https://www.ory.sh/docs/hydra/guides/kubernetes-helm-chart

However, I failed at the first step installing. Any idea? Thanks! 😃

### Reproducing the bug

I tried to run

```sh
helm install --generate-name \
    --set 'hydra.config.secrets.system=$(LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | base64 | head -c 32)' \
    --set 'hydra.config.dsn=memory' \
    --set 'hydra.config.urls.self.issuer=https://my-hydra/' \
    --set 'hydra.config.urls.login=https://my-idp/login' \
    --set 'hydra.config.urls.consent=https://my-idp/consent' \
    ory/hydra
```

### Relevant log output

However, I got error

```sh
Error: INSTALLATION FAILED: failed to download "ory/hydra"
```

### Version

N/A

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Kubernetes with Helm

### Additional Context

```sh
> kubectl version --short

Client Version: v1.23.4
Server Version: v1.22.6+k3s1
```
```sh
> helm version --short

v3.8.1+g5cb9af4
```

**Comment by Hongbo-Miao** [comment]
I succeed after running this first

```
helm repo add ory https://k8s.ory.sh/helm/charts
```

Then I can install. I think might worth adding to the document.

**Comment by Demonsthere** [comment]
Hi there. This piece of documentation is actually in the root of the documents: http://k8s.ory.sh/helm/ 😉

**Comment by Hongbo-Miao** [comment]
Oh yeah, originally I didn't find that.
I was following this tutorial https://www.ory.sh/docs/hydra/guides/kubernetes-helm-chart
Worth adding there too! 😊
