### ISSUE TITLE
Update helm chart for Ory Hydra v2.x

### ISSUE THREAD

**Issue by aeneasr** [ory/k8s#448]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Hydra 2.x will remove two flags and make them into one bool flag:

```patch
- `dangerousForceHttp` (bool): If enabled, sets the `--dangerous-force-http` flag on `hydra serve all`.
- `dangerousAllowInsecureRedirectUrls` (string[]): Sets the `--dangerous-allow-insecure-redirect-urls` flag on `hydra serve all`.
+ `dev` (bool): If true, disables critical security measures to allow easier local development. Do not use in production.
```

### Describe your ideal solution

Update the charts

### Workarounds or alternatives

None

### Version

master

**Comment by Demonsthere** [comment]
Do you foresee any other major changes? Asking because we can either `if` the charts depending on the version of hydra, or  just implement the breaking changes and point that since the new release charts only support hydra v2.0+ like we did previously.

**Comment by Demonsthere** [comment]
Closed by https://github.com/ory/k8s/releases/tag/v0.26.0 :)
