### ISSUE TITLE
Add `deployment.extraLabels` option to Ory Hydra helm chart

### ISSUE THREAD

**Issue by aeneasr** [ory/k8s#453]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Similar to Ory Keto and Ory Kratos, Ory Hydra should also support the configuration key `deployment.extraLabels`

### Describe your ideal solution

See above

### Workarounds or alternatives

None

### Version

master

**Comment by Demonsthere** [comment]
In Hydra the option is named `deployments.labels`, but it provides the same function. We could and probably should unify the naming convention across the charts 😞
