### ISSUE TITLE
High Availability for hydra in k8s

### ISSUE THREAD

**Issue by GSokol** [ory/k8s#46]
Currently, hydra couldn't start with more than one replicas. In case of using hydra as an application authorization provider (not cluster authorization provider) so to let each request pass through hydra, it seems not acceptable, especially according to fact that k8s do ton guarantees liveness of the particular pod.

**Comment by GSokol** [comment]
I understand, that this is a problem of hydra architecture, not the helm chart, but it seems to me, that, at least this issue should be related to some issue in hydra repository.

**Comment by aeneasr** [comment]
What issue are you encountering when starting multiple replicas?

Hydra does scale indefinitely, unless you're using the in-memory database provider of course.

**Comment by aeneasr** [comment]
Also, iirc, our k8s chart supports replicaCount so it should work out of the box.

**Comment by GSokol** [comment]
Oh, that really works! I used to face some problems, but everything is ok now! Sorry for troubles. I don't remember the exact issue, but it was something related to certificate (or some key) generation.
