### ISSUE TITLE
Unify automigration options 

### ISSUE THREAD

**Issue by Demonsthere** [ory/k8s#465]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

In https://github.com/ory/k8s/pull/451 a new automigration option has been introduced for kratos. We need to expand that new model into other apps to ensure consistency across the software stack. 

### Describe your ideal solution

as above

### Workarounds or alternatives

none

### Version

yes

**Comment by Demonsthere** [comment]
Closed by #466

**Comment by kubitre** [comment]
so, bad for breaking backward compatibility
