### ISSUE TITLE
helm/hydra: rework configMap and how secrets are handled

### ISSUE THREAD

**Issue by max-koehler** [ory/k8s#47]
**Is your feature request related to a problem? Please describe.**
The generation of secrets in the current helm chart are not secure, as the values are stored in plaintext as part of the configMap. 

In order to provide values for `dsn`, `secrets.system` and `secrets.cookie` someone has to set or provide values for the matching config keys such as `hydra.config.dsn`. Later in the `_helpers.tpl` the `hydra.dsn`(as an example here) will be propagated with the value of the provided key `hydra.config.dsn`. 

Once they are provided and part of the config structure they aren't removed at any time and end up in the configMap in plaintext. Eventually the configMap will be mounted as a volume for the application. 

As a result we end up having secrets we inject via environment variables in a secure way, while we are still mounting the same keys/values in plain text through the configMap.

**Describe the solution you'd like**
Remove secrets from the config structure and allow to set the keys directly:.
`hydra.config.secrets.system` -> `hydra.secrets.system`
`hydra.config.secrets.cookies` -> `hydra.secrets.cookie` 
`hydra.config.dsn` -> `hydra.dsn`
Also if those keys are provided are throughout the config object, those keys and it's values should be removed from it before the configMap is stored. 

As this is a breaking change in the current implementation, id like to get your input first but would be willing to bring the changes in as a PR.

**Comment by aeneasr** [comment]
Oh I see - we actually provide this using secrets here https://github.com/ory/k8s/blob/master/helm/charts/hydra/templates/secrets.yaml#L15-L17 and generate them from `hydra.config...` ( https://github.com/ory/k8s/blob/master/helm/charts/hydra/templates/_helpers.tpl#L70-L78 ). However, I forgot to truncate those values from the actual configmap, which is why they're leaking. If you are willing to supply a fix for that, it would be super appreciated!

**Comment by evalsocket** [comment]
Hey @aeneasr, I like to pick that issue....i think changes are in Line 76 https://github.com/ory/k8s/blob/728fc908cf04a3246b50409b35a8dfb8d7dd8bbd/helm/charts/hydra/templates/_helpers.tpl#L76

**Comment by aeneasr** [comment]
@evalsocket awesome! Unfortunately not, what we have to do is truncate/delete `hydra.config.secrets` as well as `hydra.config.dsn` before rendering it to the configmap. I'm not sure if that possible with helm templates. The config map is being rendered here:

https://github.com/ory/k8s/blob/master/helm/charts/hydra/templates/configmap.yaml#L10-L12

and basically we would need to delete keys:

- hydra.config.secrets
- hydra.config.dsn

before calling `toYaml` here.

**Comment by aeneasr** [comment]
We can probably use [set](http://masterminds.github.io/sprig/dicts.html) to unset the key before rendering

**Comment by aeneasr** [comment]
https://github.com/ory/k8s/pull/78
