### ISSUE TITLE
Inconsistent use of init & extra containers on jobs

### ISSUE THREAD

**Issue by adamstrawson** [ory/k8s#507]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The Hydra helm-chart `job` resource has an incorrectly wrapped conditional, `extraContainers` is wrapped within `extraInitContainers` conditional, meaning you cant define an extra container without also setting `extraInitContainers`.

Keto & Kratos was also missing `extraInitContainers` entirely too. 

### Reproducing the bug

`helm install -f values.yaml ory/hydra` 

```yaml
# values.yaml
job:
  extraContainers: |
    - name: helloworld
      image: helloword:latest
```

The `hellowold` sidecar container will not be included. 

### Version

0.25.3

**Comment by Demonsthere** [comment]
Closed by https://github.com/ory/k8s/pull/508
