### ISSUE TITLE
[oathkeeper] allow to add additional containers

### ISSUE THREAD

**Issue by omerlh** [ory/k8s#510]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Until ory/oathkeeper#969 is resolved, I need to add a proxy that will add authentication headers to the request to the authorization server. I would like to add a sidecar to oathkeeper chart so I could run Nginx (or any other proxy) that is capable of adding the authorization header before passing the request to upstream.

### Describe your ideal solution

Adding something like `.sidecar` to the chart with full container spec so I could define additional containers on the chart. I will probably also need to mount volumes for Nginx config / authentication to the authorization credentials.

### Workarounds or alternatives

Running the proxy as another deployment (insecure), fixing the original issue in oathkeeper or forking the chart.

### Version

latest

**Comment by Demonsthere** [comment]
Hi there!
Oathkeeper already supports extraContainers, which can be set using `.Values.deployment.extraContainers` :)
