### ISSUE TITLE
Add support for `hydra janitor` in the Hydra Helm chart

### ISSUE THREAD

**Issue by ste93cry** [ory/k8s#513]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Some tables of the database of Ory Hydra keep growing in an unbounded manner, leading to a lot of stale rows that can be cleaned up after some time passed. For this reason, the `hydra janitor` command was born, which can be run as a cron job to purge the data from the database. Unfortunately, the Helm chart does not provide any out-of-the-box way to schedule such job.

### Describe your ideal solution

Provide a `CronJob` resource in the Helm chart that can be enabled and configured via Helm values to execute the `hydra janitor` command. It should be possible to configure how often the cron job runs and which kind of things it should clean up: tokens, requests or grants (any combination of them). It should also be possible to configure the main [options](https://www.ory.sh/docs/hydra/cli/hydra-janitor#options) supported by the command, e.g. the refresh token lifespan or the batch size.

### Workarounds or alternatives

Keep things as-is and leave the implementation of the cron job to the customers

### Version

0.25.3

### Additional Context

I could be able to work on a contribution

**Comment by Demonsthere** [comment]
Hi there!
I agree that we could provide the framework of the cronjob in the helm chart, but the only sane config we could deliver would be an empty one. We should not enable the option to delete anything by default, as it may lead to undesired situations.

**Comment by ste93cry** [comment]
Absolutely agree, I didn't mean to enable it by default, I just wanted to provide the cron job definition and make it configurable in the chart.
