### ISSUE TITLE
Automigrate job does not accept `elastic-apm` as a tracer option with helm chart v0.26.0

### ISSUE THREAD

**Issue by zagr0** [ory/k8s#538]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When upgrade hydra helm chart deployment from 0.25.6 -> 0.26.0 and using `elastic-apm` as tracing config the auto migration job fails with error:
```
level=error msg=Unable to initialize Tracer. audience=application error=map[message:expected one of [jaeger, zipkin, otel, ] but got elastic-apm] service_name=Ory Hydra service_version=v2.0.1
```

### Reproducing the bug

1. use tracer as `elastic-apm'
```
    deployment:
      extraEnv:
        - name: TRACING_PROVIDER
          value: elastic-apm
```
2. do `helm upgrade ory/hydra` from 0.25.6 to 0.26.0

### Relevant log output

```shell
time=2022-11-02T13:13:10Z level=error msg=Unable to initialize Tracer. audience=application error=map[message:expected one of [jaeger, zipkin, otel, ] but got elastic-apm] service_name=Ory Hydra service_version=v2.0.1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x11cf810]

goroutine 1 [running]:
github.com/ory/x/otelx.(*Tracer).Tracer(...)
	/go/pkg/mod/github.com/ory/x@v0.0.486/otelx/otel.go:83
github.com/ory/hydra/driver.(*RegistryBase).Tracer(0xc00021f800, {0xc0001fcb00?, 0xc0009d37c0?})
	/project/driver/registry_base.go:484 +0x150
github.com/ory/hydra/driver.(*RegistrySQL).Init(0xc0009e86f0, {0x19d23f8, 0xc0001ac000}, 0x1, 0x0, {0x19cac50?, 0x23f3328?})
	/project/driver/registry_sql.go:99 +0xb1
github.com/ory/hydra/driver.NewRegistryFromDSN({0x19d23f8, 0xc0001ac000}, 0xc00057f5c0?, 0xc000173fd0?, 0x2?, 0x0?, {0x19cac50, 0x23f3328})
	/project/driver/registry.go:80 +0x86
github.com/ory/hydra/driver.New({0x19d23f8, 0xc0001ac000}, 0xc00057f4a0, {0xc000b1fcc8, 0x4, 0x0?})
	/project/driver/factory.go:98 +0x1d0
github.com/ory/hydra/cmd/cli.(*MigrateHandler).MigrateSQL(0x0?, 0xc000a5a780, {0xc000a1e640, 0x0, 0x0?})
	/project/cmd/cli/handler_migrate.go:263 +0x2f0
github.com/spf13/cobra.(*Command).execute(0xc000a5a780, {0xc000a1e600, 0x4, 0x4})
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc000a24000)
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/ory/hydra/cmd.Execute()
	/project/cmd/root.go:118 +0x3a
main.main()
	/project/main.go:31 +0x69
```
```


### Relevant configuration

_No response_

### Version

0.26.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm

### Additional Context

_No response_

**Comment by aeneasr** [comment]
We switched from OpenTracing, which is deprecated, to OpenTelemetry. Unfortunately aws-apm does not yet support it (or at least did not support it when we implemented it)

**Comment by zagr0** [comment]
Ok, got it.
Seems like apm server supports otel protocol, will try to use otel instead
https://www.elastic.co/guide/en/apm/guide/current/open-telemetry.html

**Comment by Demonsthere** [comment]
Hey @zagr0 if it works for you, i'd be happy to add a section in the documentation on how to add it, to make it easier for others :)
