### ISSUE TITLE
hydra-automigrate is logging database DSN with password

### ISSUE THREAD

**Issue by juusujanar** [ory/k8s#55]
**Describe the bug**

Hydra auto-migrate init container in Kubernetes logs multiple lines, which include the full DSN (which includes the database password). Info log level lines are also there, which hide database user and password with asterisks.

**To Reproduce**

1. Enable autoMigrate in helm chart
2. Deploy the chart.
3. Check initContainer logs.

**Expected behavior**

Database password does not get logged.

**Environment**

* Docker image oryd/hydra:v1.0 with image ID oryd/hydra@sha256:c60c647f6f34502ec6807a8423fb9cde0128abed3128c3d203750b68bb2ef81f (Docker Hub gives timestamp 3 days ago)
* Tested in a Google Kubernetes Engine cluster.

**Additional context**

Logs from the init container pod.
```
➜ kubectl logs -f hydra-58fd8cb8dd-h5tnm -c hydra-automigrate
Config file not found because "Config File ".hydra" Not Found in "[/]""
migrate dsn set viper 2: postgres://hydra:<PASSWORD>@<HOST>:5432/hydra
migrate dsn set viper 3: postgres://hydra:<PASSWORD>@<HOST>:5432/hydra
time="2019-09-25T21:39:30Z" level=info msg="No tracer configured - skipping tracing setup"
time="2019-09-25T21:39:30Z" level=info msg="Establishing connection with SQL database backend" dsn="postgres://*:*@<HOST>:5432/hydra?"
time="2019-09-25T21:39:30Z" level=info msg="Successfully connected to SQL database backend" dsn="postgres://*:*@<HOST>:5432/hydra?"
Got dsn: postgres://hydra:<PASSWORD>@<HOST>:5432/hydraThe following migration is planned:

| DRIVER | MODULE | ID | # |        QUERY         |
|--------|--------|----|---|----------------------|
|--------|--------|----|---|----------------------|
Successfully applied 0 SQL migrations!
```

**Comment by aeneasr** [comment]
Thank you for the report - this will be fixed with the linked PR and released as 1.0.4.
