### ISSUE TITLE
CRD oathkeeper-maester did not contain errors config 

### ISSUE THREAD

**Issue by Peelz** [ory/k8s#559]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

For k8s [Crd](https://github.com/ory/k8s/blob/master/helm/charts/oathkeeper-maester/crds/crd-rules.yaml) I can't see how to config errors handler

### Describe your ideal solution

-

### Workarounds or alternatives

-

### Version

0.27.0

**Comment by Demonsthere** [comment]
Closed by https://github.com/ory/k8s/pull/596
