### ISSUE TITLE
[CI] Test both migration patterns

### ISSUE THREAD

**Issue by Demonsthere** [ory/k8s#564]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Currently we only test one set of `values.yaml` for applications. This causes us to test either initContainer or job automigration deployment patterns, and we can be (and have been) blind to changes that cause errors, like seen in https://github.com/ory/k8s/pull/563. To fix that we need to create copies or layers of overrides file to test both cases

### Describe your ideal solution

hacks/values/hydra.yaml -> Default overrides for the application
hacks/values/hydra-migration-job -> Subset of overrides to use specific migrations
hacks/values/hydra-migration-init -> Other subset

then test it using layers like `helm template hydra . -f values.yaml -f hydra-migration-job.yaml

### Workarounds or alternatives

have a ton of files with minor differences or set overrides using `--set`?

### Version

yes

**Comment by DanyHenriquez** [comment]
@Demonsthere You could use Helmfile with a values go template for this. That way you can have multiple setups to test without adding too much complexity

**Comment by Demonsthere** [comment]
Hello there :) 
I was initially planning on using [skaffold](https://skaffold.dev), to create multiple profiles and test them, but Helmfile is also a valid option. 
The point would be to have a matrix CI definition, which runs multiple cases for each chart, and runs in parallel to each other. 

Feel free to reach out to me in the [opensource slack](https://join.slack.com/t/ory-community/shared_invite/zt-1p5lp2ywy-7YfHyQvB7oCwyk7eLIJhvQ) if you want to discuss it in real time or a call.
Cheers!
