### ISSUE TITLE
Configurable annotations

### ISSUE THREAD

**Issue by koenmtb1** [ory/k8s#57]
**Is your feature request related to a problem? Please describe.**
I'm trying to deploy Oathkeeper behind Ambassador and for that to work you have to add annotations to the Service of Oathkeeper. Right now this isn't configurable in the chart.

**Describe the solution you'd like**
A way to add annotations with either a file or when deploying with an extra variable that can be passed.

**Describe alternatives you've considered**
The only solution right now is to fork and edit it myself but I think this is a key feature that should be implemented into this chart.

**Comment by aeneasr** [comment]
Ah yeah, that's a good idea. It should be done similarly to the way we allow deployment annotations (https://github.com/ory/k8s/blob/master/helm/charts/oathkeeper/values.yaml#L117). Would you be up for a PR?

**Comment by aeneasr** [comment]
Closed because resolved by #58
