### ISSUE TITLE
Docs: Kratos Helm chart doc is not rendered correctly on k8s.ory.sh

### ISSUE THREAD

**Issue by MichaelMarner** [ory/k8s#575]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The hosted Helm docs for Kratos:

https://k8s.ory.sh/helm/kratos.html

Do not render the sample yaml correctly. Specifically, the section about supplying an identity schema with a file using `--set-file`, should look like this:

```
# values.yaml
kratos:
  identitySchemas:
    <schema-name>.schema.json: |-
      {{ .Values.<your-key> }}
```

Github renders this correctly, as shown here:

https://github.com/ory/k8s/blob/master/docs/helm/kratos.md#identity-schemas

However, the _vital_ `{{.Values<your-key<}}` is not rendered at all on the generated HTML:

<img width="901" alt="Screenshot 2023-03-07 at 10 42 02 pm" src="https://user-images.githubusercontent.com/298563/223418679-bd23758c-0075-4c03-98c3-f05dbe40627f.png">

### Reproducing the bug

N/A - This is an error in the generated documentation.

### Relevant log output

```shell
N/A
```

### Relevant configuration

```yml
N/A
```

### Version

N/A

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by till** [comment]
@MichaelMarner thank you! :)

Can confirm that this is still an issue, and very confusing for those who are not super familiar with helm. :D

**Comment by Demonsthere** [comment]
Yeah, it's the github pages based rendering 😞 The file renders correctly as a md, and even local md -> html shows it correctly. I have tried updating the pages theme, but it looks the same. Don't really know what we can do here 😞
