### ISSUE TITLE
kartos helm chart values should be evaluated by tpl function

### ISSUE THREAD

**Issue by bkomraz1** [ory/k8s#586]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

I can't use {{.Values.myVal}} in kratos's value file. Instead of it I have specify fixed values per environment

### Describe your ideal solution

evaluate values by tpl function 

### Workarounds or alternatives

helm chart values.yaml configuration per environment

### Version

Kratos helm chart 0.28.1

**Comment by Demonsthere** [comment]
Closed by https://github.com/ory/k8s/pull/587
