### ISSUE TITLE
deploy image of oathkeeper-maester to arm64

### ISSUE THREAD

**Issue by 0xfourzerofour** [ory/k8s#623]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

I can see on the ory documentation that oathkeeper works on arm64 images however the helm chart relies on the oathkeeper-maester controller which does not support arm64 right now. 

with the current setup on an arm64 cluster (graviton3) I get the following error

```
exec /manager: exec format error    
```

### Describe your ideal solution

All that needs to be done is deploy a version with the arm64 flag and it should be good to go.

### Workarounds or alternatives

NA

### Version

latest

**Comment by 0xHexE** [comment]
+1

**Comment by 0xHexE** [comment]
I found out that the maester is no longer being activity maintained. I believe there is a workaround without maester.

```hcl
set {
  name  = "maester.enabled"
  value = "false"
}
```

**Comment by 0xfourzerofour** [comment]
@0xHexE awesome I will give that a go!

**Comment by Demonsthere** [comment]
The arm based images have been added in https://github.com/ory/oathkeeper-maester/releases/tag/v0.1.9 
Just need to bump the values in the charts :)

**Comment by markusheinemann** [comment]
Just override the oathkeeper-maester container tag in your `values.yaml`

```yaml
oathkeeper-maester:
  tag: "v0.1.10-arm64"
  pullPolicy: IfNotPresent
```
