### ISSUE TITLE
Unable to rotate secretsCookie in k8s helm chart

### ISSUE THREAD

**Issue by AmiSMB** [ory/k8s#643]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When trying to supply the helm chart for Hydra with the same value I always end up with the secrets that have been created prefixed with [ and suffixed with ] as I am supplying a list which is correct as per the [key rotation documentation](https://www.ory.sh/docs/hydra/self-hosted/secrets-key-rotation). Looking at [_helpers.tpl](https://github.com/ory/k8s/blob/v0.36.0/helm/charts/hydra/templates/_helpers.tpl) you can see the reason is that the value is not being handled in the same way as the secretsSystem.

### Reproducing the bug

helm install \
    --set 'hydra.config.secrets.system=["test","test1"]' \
    --set 'hydra.config.secrets.cookie=["test","test1"]' \
    --set 'hydra.config.dsn=memory' \
    --set 'hydra.config.urls.self.issuer=https://my-hydra/' \
    --set 'hydra.config.urls.login=https://my-idp/login' \
    --set 'hydra.config.urls.consent=https://my-idp/consent' \
    ory/hydra

kubectl get secrets/hydra --template={{.data.secretsSystem}} | base64 -d ; echo
["test","test1"]
kubectl get secrets/hydra --template={{.data.secretsCookie}} | base64 -d ; echo
[test [test1]]

### Version

v2.1.2 Hydra 0.36.0 Helm chart

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm

**Comment by Demonsthere** [comment]
Thanks for the report :) I have unified the logic to handle the array better
