### ISSUE TITLE
DSN environmental variable is not set optionally

### ISSUE THREAD

**Issue by blumTom** [ory/k8s#659]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Location:
https://github.com/ory/k8s/blob/d3ffdadf111d535729a59e72998ec7cee8d457f9/helm/charts/kratos/templates/cleanup-cron-job.yaml#L74

The condition does not evaluate properly.
The intention here is to set the DSN environmental variable optionally, but with this condition it is always set.
However, it is a good idea to set the DSN environmental variable optionally to give the user the possibility to define a custom source of this value via the "cleanupCronjobExtraEnv" variable.
In addition to that this should be consistent to all other occurrences of DSN environmental variable definitions.

### Reproducing the bug

Do not set the dsn config value.

### Relevant configuration

```yml
dsn:
```

### Version

0.38.0 (helm version)

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by dlahn** [comment]
fixed by #678

**Comment by Demonsthere** [comment]
closed by https://github.com/ory/k8s/pull/678
