### ISSUE TITLE
config.courier.template_override_path  not used.

### ISSUE THREAD

**Issue by spreeker** [ory/k8s#690]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

In our attemts to customize the email templates we encounted some problems. After goging thtough the source code in the helm chart following variable is mentioned: `config.courier.template_override_path`

   https://github.com/ory/k8s/blob/master/helm/charts/kratos/values.yaml#L167
   
   BUT where and how does in end up  used and deployed in the kratos configuration. I could not figure this out. Am I mising somehting?

### Reproducing the bug

create a values.example.yaml with custom email templates: 

+ helm upgrade --install --namespace ory --values ./keto/values.example.yml --version 0.41.0 keto ory/keto

### Relevant configuration

```yml
kratos:  
  config:
    courier:
      smtp: {}
      #template_override_path: /conf/courier-templates

seems to do nothing.
```

### Version

0.41.0

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

Kubernetes with Helm

### Additional Context

I tried to reverse engineer and search where and how kratos email templates are configured.

**Comment by spreeker** [comment]
solved!!  in the example settings 'verification' should be 'verification_code' created a pull request.

**Comment by Demonsthere** [comment]
Closing as https://github.com/ory/k8s/pull/692 has been merged
