### ISSUE TITLE
ory/kratos  0.45.0 is packaged with 1.1.0 instead of 1.2.0

### ISSUE THREAD

**Issue by faraonc** [ory/k8s#694]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

```
ory/kratos                      0.45.0          v1.1.0                  A ORY Kratos Helm chart for Kubernetes            
```

I think ory/kratos  0.45.0 is packaged with the wrong default values. 
- https://github.com/ory/k8s/blob/master/helm/charts/kratos/Chart.yaml#L2
- https://github.com/ory/k8s/blob/master/helm/charts/kratos/values.yaml#L18

### Reproducing the bug

```
$ helm repo add ory https://k8s.ory.sh/helm/charts
$ helm repo update
$ helm show values ory/kratos --version=0.45.0 > a.yaml
```

Observe the value for tag:
```
tag: v1.1.0
```

### Version

0.45.0  

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

### Additional Context

I just overridden the tag, but it looks like an oversight on the release process.

**Comment by Demonsthere** [comment]
Hi there! The bump to 1.2 was not included in the 0.45.0 release :) https://github.com/ory/k8s/compare/v0.45.0...master
