### ISSUE TITLE
hydra-maester: redirectURIs and clientSecret not supported by latest release 0.0.47

### ISSUE THREAD

**Issue by ms42Q** [ory/k8s#94]
#### Description

In the [docs](https://k8s.ory.sh/helm/hydra-maester.html) the properties `redirectURIs` and `clientSecret` of the crd are mentioned. But the current version 0.0.47 doesn't support those values. I think those values are very essential. I cannot use hydra-maester without them.

#### Solution
Add a new release after this commit 9c1566c9781e5709217360a6ab01ab5664120398. 

https://github.com/ory/k8s/commit/9c1566c9781e5709217360a6ab01ab5664120398#diff-aa0d96bd300dbf559b37535472d28f74

##### Alternative
Change the docs to be consistent with 0.0.47

#### Comments
Is there a version that I can use for now that does include those properties?

**Comment by aeneasr** [comment]
Pending PR #87

**Comment by ms42Q** [comment]
Sure, I know. But why not just add another tag so that master can be used as claimed by the docs. #87 is quite big as well so I assume it will still take some time until its merged and released. I can't wait another week so I in that case I guess I have to come up with something myself, right?

**Comment by aeneasr** [comment]
I think this has been resolved
