### ISSUE TITLE
Installation fails with helm3 on minikube

### ISSUE THREAD

**Issue by skuro** [ory/k8s#96]
**Describe the bug**

The `ory/hydra` chart fails to install under `helm3`

**To Reproduce**

1. install [helm3](https://github.com/helm/helm/releases/tag/v3.0.0)
2. `helm repo add ory https://k8s.ory.sh/helm/charts`
3. `helm repo update`
4. try to run `helm install` as per the [official guide](https://k8s.ory.sh/helm/hydra.html)
5. the installation fails with `Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(RoleBinding.roleRef): unknown field "namespace" in io.k8s.api.rbac.v1beta1.RoleRef`

**Expected behavior**

The helm chart is installed successfully

**Environment**

* Version: v1.0.0-rc.14_oryOS.12
* Environment: helm v3.0.0, minikube v1.5.2 on Ubuntu

**Comment by aeneasr** [comment]
Helm3 is very new, please use Helm2 for the time being when working with these charts.

**Comment by skuro** [comment]
thanks for the tip @aeneasr, although I actually already did that :-) Still thought it was good to track this one down with its own issue

**Comment by matdehaast** [comment]
This can be worked around by disabling the use of the maester. Use the following flag when installing the chart

```
 --set 'maester.enabled=false' 
```

**Comment by skuro** [comment]
good to know, thanks @matdehaast
